import pymongo

myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["setsgame"]
mycol = mydb["cards"]

mylist = [
  {"_id": 1, "color": "green", "shape": "diamond", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_green_filled_1.svg"},
  {"_id": 2, "color": "green", "shape": "diamond", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_green_filled_2.svg"},
  {"_id": 3, "color": "green", "shape": "diamond", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_green_filled_3.svg"},
  {"_id": 4, "color": "green", "shape": "diamond", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_green_outline_1.svg"},
  {"_id": 5, "color": "green", "shape": "diamond", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_green_outline_2.svg"},
  {"_id": 6, "color": "green", "shape": "diamond", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_green_outline_3.svg"},
  {"_id": 7, "color": "green", "shape": "diamond", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_green_stripes_1.svg"},
  {"_id": 8, "color": "green", "shape": "diamond", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_green_stripes_2.svg"},
  {"_id": 9, "color": "green", "shape": "diamond", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_green_stripes_3.svg"},
  {"_id": 10, "color": "red", "shape": "diamond", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_red_filled_1.svg"},
  {"_id": 11, "color": "red", "shape": "diamond", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_red_filled_2.svg"},
  {"_id": 12, "color": "red", "shape": "diamond", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_red_filled_3.svg"},
  {"_id": 13, "color": "red", "shape": "diamond", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_red_stripes_1.svg"},
  {"_id": 14, "color": "red", "shape": "diamond", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_red_stripes_2.svg"},
  {"_id": 15, "color": "red", "shape": "diamond", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_red_stripes_3.svg"},
  {"_id": 16, "color": "red", "shape": "diamond", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_red_outline_1.svg"},
  {"_id": 17, "color": "red", "shape": "diamond", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_red_outline_2.svg"},
  {"_id": 18, "color": "red", "shape": "diamond", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_red_outline_3.svg"},
  {"_id": 19, "color": "purple", "shape": "diamond", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_purple_filled_1.svg"},
  {"_id": 20, "color": "purple", "shape": "diamond", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_purple_filled_2.svg"},
  {"_id": 21, "color": "purple", "shape": "diamond", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_purple_filled_3.svg"},
  {"_id": 22, "color": "purple", "shape": "diamond", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_purple_stripes_1.svg"},
  {"_id": 23, "color": "purple", "shape": "diamond", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_purple_stripes_2.svg"},
  {"_id": 24, "color": "purple", "shape": "diamond", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_purple_stripes_3.svg"},
  {"_id": 25, "color": "purple", "shape": "diamond", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_purple_outline_1.svg"},
  {"_id": 26, "color": "purple", "shape": "diamond", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_purple_outline_2.svg"},
  {"_id": 27, "color": "purple", "shape": "diamond", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\diamond_purple_outline_3.svg"},
  {"_id": 28, "color": "green", "shape": "Oval", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_green_Filled_1.svg"},
  {"_id": 29, "color": "green", "shape": "Oval", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_green_Filled_2.svg"},
  {"_id": 30, "color": "green", "shape": "Oval", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_green_Filled_3.svg"},
  {"_id": 31, "color": "green", "shape": "Oval", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_green_outline_1.svg"},
  {"_id": 32, "color": "green", "shape": "Oval", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_green_outline_2.svg"},
  {"_id": 33, "color": "green", "shape": "Oval", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_green_outline_3.svg"},
  {"_id": 34, "color": "green", "shape": "Oval", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_green_stripes_1.svg"},
  {"_id": 35, "color": "green", "shape": "Oval", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_green_stripes_2.svg"},
  {"_id": 36, "color": "green", "shape": "Oval", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_green_stripes_3.svg"},
  {"_id": 37, "color": "red", "shape": "Oval", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_red_Filled_1.svg"},
  {"_id": 38, "color": "red", "shape": "Oval", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_red_Filled_2.svg"},
  {"_id": 39, "color": "red", "shape": "Oval", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_red_Filled_3.svg"},
  {"_id": 40, "color": "red", "shape": "Oval", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_red_stripes_1.svg"},
  {"_id": 41, "color": "red", "shape": "Oval", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_red_stripes_2.svg"},
  {"_id": 42, "color": "red", "shape": "Oval", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_red_stripes_3.svg"},
  {"_id": 43, "color": "red", "shape": "Oval", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Ovald_red_outline_1.svg"},
  {"_id": 44, "color": "red", "shape": "Oval", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_red_outline_2.svg"},
  {"_id": 45, "color": "red", "shape": "Oval", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_red_outline_3.svg"},
  {"_id": 46, "color": "purple", "shape": "Oval", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_purple_Filled_1.svg"},
  {"_id": 47, "color": "purple", "shape": "Oval", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_purple_Filled_2.svg"},
  {"_id": 48, "color": "purple", "shape": "Oval", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_purple_Filled_3.svg"},
  {"_id": 49, "color": "purple", "shape": "Oval", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_purple_stripes_1.svg"},
  {"_id": 50, "color": "purple", "shape": "Oval", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_purple_stripes_2.svg"},
  {"_id": 51, "color": "purple", "shape": "Oval", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_purple_stripes_3.svg"},
  {"_id": 52, "color": "purple", "shape": "Oval", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_purple_outline_1.svg"},
  {"_id": 53, "color": "purple", "shape": "Oval", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_purple_outline_2.svg"},
  {"_id": 54, "color": "purple", "shape": "Oval", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\Oval_purple_outline_3.svg"},
  {"_id": 55, "color": "green", "shape": "squiggle", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_green_filled_1.svg"},
  {"_id": 56, "color": "green", "shape": "squiggle", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_green_filled_2.svg"},
  {"_id": 57, "color": "green", "shape": "squiggle", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_green_filled_3.svg"},
  {"_id": 58, "color": "green", "shape": "squiggle", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_green_outline_1.svg"},
  {"_id": 59, "color": "green", "shape": "squiggle", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_green_outline_2.svg"},
  {"_id": 60, "color": "green", "shape": "squiggle", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_green_outline_3.svg"},
  {"_id": 61, "color": "green", "shape": "squiggle", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_green_stripes_1.svg"},
  {"_id": 62, "color": "green", "shape": "squiggle", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_green_stripes_2.svg"},
  {"_id": 63, "color": "green", "shape": "squiggle", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_green_stripes_3.svg"},
  {"_id": 64, "color": "red", "shape": "squiggle", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_red_filled_1.svg"},
  {"_id": 65, "color": "red", "shape": "squiggle", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_red_filled_2.svg"},
  {"_id": 66, "color": "red", "shape": "squiggle", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_red_filled_3.svg"},
  {"_id": 67, "color": "red", "shape": "squiggle", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_red_stripes_1.svg"},
  {"_id": 68, "color": "red", "shape": "squiggle", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_red_stripes_2.svg"},
  {"_id": 69, "color": "red", "shape": "squiggle", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_red_stripes_3.svg"},
  {"_id": 70, "color": "red", "shape": "squiggle", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_red_outline_1.svg"},
  {"_id": 71, "color": "red", "shape": "squiggle", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_red_outline_2.svg"},
  {"_id": 72, "color": "red", "shape": "squiggle", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_red_outline_3.svg"},
  {"_id": 73, "color": "purple", "shape": "squiggle", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_purple_filled_1.svg"},
  {"_id": 74, "color": "purple", "shape": "squiggle", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_purple_filled_2.svg"},
  {"_id": 75, "color": "purple", "shape": "squiggle", "fill_type": "filled", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_purple_filled_3.svg"},
  {"_id": 76, "color": "purple", "shape": "squiggle", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_purple_stripes_1.svg"},
  {"_id": 77, "color": "purple", "shape": "squiggle", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_purple_stripes_2.svg"},
  {"_id": 78, "color": "purple", "shape": "squiggle", "fill_type": "stripes", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_purple_stripes_3.svg"},
  {"_id": 79, "color": "purple", "shape": "squiggle", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_purple_outline_1.svg"},
  {"_id": 80, "color": "purple", "shape": "squiggle", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_purple_outline_2.svg"},
  {"_id": 81, "color": "purple", "shape": "squiggle", "fill_type": "outline", "image_file_path": "C:\Users\mukeet\Documents\setsgame\squiggle_purple_outline_3.svg"},



]

x = mycol.insert_many(mylist)

#print list of the _id values of the inserted documents:
print(x.inserted_ids)